ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

define PINFO
PINFO DESCRIPTION=Set or get date from realtime clock
endef


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

-include $(PROJECT_ROOT)/roots.mk

INSTALLDIR=sbin

EXTRA_INCVPATH += $(PROJECT_ROOT)/../../../hardware/startup/lib/public
LDFLAGS+=-Wl,--no-undefined

USEFILE=$(PROJECT_ROOT)/$(NAME).use
